### PR TITLE
Fix broken routing in development mode. 

### LINKED ISSUE #233: Broken routing
As @denar90 noticed, we have broken routing with development mode. I suppose this issue is related to problems with navigation using `iframe`.  Gonna try to fix that.

**Step to reproduce:**

1. `git clone https://github.com/brunch/brunch.github.io && cd brunch.github.io`
1. `git checkout source`
1. `npm install`
1. `npm start`
1. Go to `http://localhost:3333` and then click any internal link. You'll stay at the home page anyway.

> If you really need to go the specific route, please add `.html` extension after each of route, e.g: `http://localhost:3333/docs/getting-started` → `http://localhost:3333/docs/getting-started.html` and here you go.

### PR DESCRIPTION
**Pull request by denysdovhan**
Fix #233.

### CODE REVIEW

File: app/init.js [hunk 1]
```diff
@@ -73,6 +73,21 @@ function deferIframe() {
   });
 }
 
+// Just a small hack
+// Add `.html` extansion for each of internal links
+// Fix for: https://github.com/brunch/brunch.github.io/issues/233
+if (process.env.NODE_ENV === 'development') {
+  [...document.querySelectorAll('a[href]')]
+    .filter(link => {
+      const href = link.getAttribute('href');
```
Comment (shvaikalesh) [inline app/init.js]: `const {href} = link`

File: app/init.js [hunk 2]
```diff
@@ -73,6 +73,21 @@ function deferIframe() {
...
+      return href !== '/' && href.startsWith('/');
+    })
+    .forEach(link => {
+      const href = link.getAttribute('href');
```
Comment (shvaikalesh) [inline app/init.js]: link.href += '.html'
